// JsFromRoutes CacheKey ed29981c6c20608124e30e0cea9084bb
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/tables/:table_id/rows/:row_id/cells'),
  create: /* #__PURE__ */ definePathHelper('post', '/tables/:table_id/rows/:row_id/cells'),
  new: /* #__PURE__ */ definePathHelper('get', '/tables/:table_id/rows/:row_id/cells/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/tables/:table_id/rows/:row_id/cells/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/tables/:table_id/rows/:row_id/cells/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/tables/:table_id/rows/:row_id/cells/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/tables/:table_id/rows/:row_id/cells/:id'),
}
