// JsFromRoutes CacheKey ae71539a4222a7b5aa2b50ab11c861f0
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/t/:table_id/rows/:row_id/cells'),
  create: /* #__PURE__ */ definePathHelper('post', '/t/:table_id/rows/:row_id/cells'),
  new: /* #__PURE__ */ definePathHelper('get', '/t/:table_id/rows/:row_id/cells/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/t/:table_id/rows/:row_id/cells/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/t/:table_id/rows/:row_id/cells/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/t/:table_id/rows/:row_id/cells/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/t/:table_id/rows/:row_id/cells/:id'),
}
