// JsFromRoutes CacheKey a67bac06b7472d4b6da4159df8b33855
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/t/:table_npi/rows/:row_id/cells'),
  create: /* #__PURE__ */ definePathHelper('post', '/t/:table_npi/rows/:row_id/cells'),
  new: /* #__PURE__ */ definePathHelper('get', '/t/:table_npi/rows/:row_id/cells/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/t/:table_npi/rows/:row_id/cells/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/t/:table_npi/rows/:row_id/cells/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/t/:table_npi/rows/:row_id/cells/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/t/:table_npi/rows/:row_id/cells/:id'),
}
