// JsFromRoutes CacheKey 1a156a41514c390b83d02cb354cedc8f
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/t/:table_id/columns'),
  create: /* #__PURE__ */ definePathHelper('post', '/t/:table_id/columns'),
  new: /* #__PURE__ */ definePathHelper('get', '/t/:table_id/columns/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/t/:table_id/columns/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/t/:table_id/columns/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/t/:table_id/columns/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/t/:table_id/columns/:id'),
}
