// JsFromRoutes CacheKey eadd229aa92df1c8c7f200acebf29fb6
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/tables/:table_id/columns'),
  create: /* #__PURE__ */ definePathHelper('post', '/tables/:table_id/columns'),
  new: /* #__PURE__ */ definePathHelper('get', '/tables/:table_id/columns/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/tables/:table_id/columns/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/tables/:table_id/columns/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/tables/:table_id/columns/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/tables/:table_id/columns/:id'),
}
