// JsFromRoutes CacheKey 47064cbbf953928c08e4b08e124ba5c4
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/t/:table_npi/columns'),
  create: /* #__PURE__ */ definePathHelper('post', '/t/:table_npi/columns'),
  new: /* #__PURE__ */ definePathHelper('get', '/t/:table_npi/columns/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/t/:table_npi/columns/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/t/:table_npi/columns/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/t/:table_npi/columns/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/t/:table_npi/columns/:id'),
}
