// JsFromRoutes CacheKey 235c6832f72611fbb583775041bd3d4e
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/t/:table_npi/reactions'),
  create: /* #__PURE__ */ definePathHelper('post', '/t/:table_npi/reactions'),
  show: /* #__PURE__ */ definePathHelper('get', '/t/:table_npi/reactions/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/t/:table_npi/reactions/:id'),
}
