// JsFromRoutes CacheKey 817fbdc0e58caf6f16610f971818f995
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/t/:table_npi/rows'),
  create: /* #__PURE__ */ definePathHelper('post', '/t/:table_npi/rows'),
  new: /* #__PURE__ */ definePathHelper('get', '/t/:table_npi/rows/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/t/:table_npi/rows/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/t/:table_npi/rows/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/t/:table_npi/rows/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/t/:table_npi/rows/:id'),
}
