// JsFromRoutes CacheKey efaeccde1646d2650cc0b8c9550959bc
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/tables/:table_id/rows'),
  create: /* #__PURE__ */ definePathHelper('post', '/tables/:table_id/rows'),
  new: /* #__PURE__ */ definePathHelper('get', '/tables/:table_id/rows/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/tables/:table_id/rows/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/tables/:table_id/rows/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/tables/:table_id/rows/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/tables/:table_id/rows/:id'),
}
