// JsFromRoutes CacheKey 41d08b7a90236e5c077a7f45d0ce70fd
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/t/:table_id/rows'),
  create: /* #__PURE__ */ definePathHelper('post', '/t/:table_id/rows'),
  new: /* #__PURE__ */ definePathHelper('get', '/t/:table_id/rows/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/t/:table_id/rows/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/t/:table_id/rows/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/t/:table_id/rows/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/t/:table_id/rows/:id'),
}
