// JsFromRoutes CacheKey bd8d619fc26c38e3035c7347d6667200
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/spaces/:space_npi/tables'),
  new: /* #__PURE__ */ definePathHelper('get', '/spaces/:space_npi/tables/new'),
  show: /* #__PURE__ */ definePathHelper('get', '/spaces/:space_npi/tables/:id'),
}
