// JsFromRoutes CacheKey 9fa5f8abcf4aa058c90ae4cddaec46f0
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/spaces/:space_npi/tables'),
  new: /* #__PURE__ */ definePathHelper('get', '/spaces/:space_npi/tables/new'),
  show: /* #__PURE__ */ definePathHelper('get', '/tables/:id'),
}
