// JsFromRoutes CacheKey 3303b4b916e0a841bde0e88537fcfc32
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/tables'),
  create: /* #__PURE__ */ definePathHelper('post', '/tables'),
  new: /* #__PURE__ */ definePathHelper('get', '/tables/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/tables/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/tables/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/tables/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/tables/:id'),
}
