// JsFromRoutes CacheKey 160eedb7161a3bfa5028d2fb2c86d39b
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  restore: /* #__PURE__ */ definePathHelper('post', '/t/:table_id/versions/:id/restore'),
  index: /* #__PURE__ */ definePathHelper('get', '/t/:table_id/versions'),
  show: /* #__PURE__ */ definePathHelper('get', '/t/:table_id/versions/:id'),
}
