fontawesome:
    auth_token: ENC[AES256_GCM,data:AmsjrazW5SzvnPVggrF5dJqdyatClZqhv5rYUT9FK58CdqBWEFR7OK06,iv:NebMnfEobObvnFkajAAFSBRmEBhKwg76Ar/dt4JUInU=,tag:V8vuVqz0MCKtNUOTHI+pQw==,type:str]
sops:
    age:
        - recipient: age193z7fgdkklf8f290ye6zj8ee07g6rudls8hhpfqsj6c6tms2fshsxk9lfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsckV2VUF6NVMvcG55aU4z
            MEU4aXFER2xkdHNRSWJ4c3RBQ1JCNDdXZGhFClVRV1hpUTNxZHhxWFFoUUk1bHFQ
            cHc4NTh6ck9LYnNCMHpud3NZQWE3R1EKLS0tIEVZcmt3RG1tYkd5c3JqWENqKzZX
            eHRUZW15VWhldFhoajhHK3FqdFBMVE0KVgGfAi6zGA69oMOynly6YDuBQeeYKv05
            iaEoEjcQmCNbh44HZWMQ/j2CJcxdWe6Kp5wKwmQ1wnRw2c1QPYLpJA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18p3re8vk23zc4sepnl6f83ljl4zglgxzacuzn9meg4egfhwmmp9scn5d3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraTF1RXZMaGtkU2pGa2Iy
            YUlSc3ZkMHhKcnRnYVEya1pTTXlQa0c5bTJnClVNNTM0K25aTkJZQVdmMnR0NFJD
            bHRUaFQyNjAzYVhhMDQ0U0ErdjEycDAKLS0tIDhYZUozRjFCOEdxWjZ2dHJkSE5B
            UytNTlpRajhTVTFnd2NlZ3NOTkdNNFkK6GP639+xs2Mzqatqsf+orczwz3TatrEg
            dRCZp/g3YyoIBN1l992GL6zGePTuYFSGqgSGHgxF7A7JA2HIdi8STA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1et3rc4fv40lc4czn9ug7ryvcmw2gfs2mls8c5ca0xcr2pvv9tdys4p0yv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Q1pVa2pwUUEwZExCMEdG
            S1pVb0F5c2ZmaWZOd0E3K0JWdFF6RmVqbmtJCkdXeThOc3YyRUplbnJoYkJ0OFNh
            QzZVY1QreG1DNndUd2ZLWVRFeEhvUm8KLS0tIE1RbFZTdDdmM1JsQ3p6cVFFaEJw
            ZkFvcWRWWVRERk1wWkxvTFVPTm5ORkUKdyv9EW1bu1syd5tF3u0LgRgOhOQlVcGh
            cyr5jIkgICBdcrWZVAWKjuU8Lu+diY9VXF91RlKnYsKynV7RL8JWUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-08T07:13:45Z"
    mac: ENC[AES256_GCM,data:mEHsafL1WvsnEx2X+DRAaBXOM8tpqbBSgPhfKESwXpjyW8EMK4SwInJ6Bdio6z+FHhQ+/jdB6KHJsD07Yqb7O0BbUex5UT1fcPi5qL7/bIeNgFWOuQdzm9IJHR4ZGc3aojRH8N20aKrJhBALqmf3Dq1SN3SgvzVqDphmrwl6jQc=,iv:UPMnAjZ2hWI3dSjWRqhp+vbCriPLy86dU9rlJspLbJ8=,tag:0KIoIMpmNJLT1+EByojHGw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
