#ENC[AES256_GCM,data:E0/I1ONw5kf74Tc4cn0oYC+/J2zfTivCFECtM4SoTMs=,iv:zv+dI3BSzg65PU3bQUoiiBuhEdQG1TWqoUbts18SV5Q=,tag:k8gEo4f4AU/lu90VWiyFGw==,type:comment]
#ENC[AES256_GCM,data:5NTBmj3/WonMpeSNTpheWlP14cEmF9Y/RRqnogasysyTnmY02v9IjkE=,iv:m/feM7hQa/nsQxoXSEZrWQCTUvocCMBX1PzdpXW+V8o=,tag:u19kmsbDOSynqD4VJFG3tA==,type:comment]
#ENC[AES256_GCM,data:UHqokAw/XcWmaXyHD9TK+8lkQ/CN0P5TKihgfNWuXwrt,iv:x5uoadY9FDk/XnT68/OG3l9mOB1nb1+O5OtjrZJEwj8=,tag:ZkR3anJ48fzlD1iF3YllKg==,type:comment]
rails:
    master_key: ENC[AES256_GCM,data:eyktCbWYlHVSbo04aT/7luAcleeX9Ic35JkNIjPapVU=,iv:/w5aBHsmSrTwA7/KhDBSijsf7JTZMg2SpS96KHniPWk=,tag:HAAsBH6vP5UmgIXOrpaThA==,type:str]
#ENC[AES256_GCM,data:mlfFtKh9q+164QjRzC55y86qj4soqTKmBLyMksdYrvQM5fy7MqhJ86E=,iv:+sG/WlFHm/kDGkjhAg3u1o1twEd4DXPfpHyrj4hmZKE=,tag:5gboVpe1BLJgd7X5zT8CbQ==,type:comment]
fontawesome:
    auth_token: ENC[AES256_GCM,data:HLQde2ayGLVuy2vODtZE6LTDquaFPYiSipUNS+7RGM1j8VZ6Lec1dVXo,iv:M2KK+T5xB4k3vE4tY5A8dnCxNRjEQi1C09LT54LeHoY=,tag:CyRpFCUyc8BYRG+hQsrhbQ==,type:str]
#ENC[AES256_GCM,data:eMN3c2gjZ2lxpzBdTw3rwUEo57cauArtXgKJchl9hCK0,iv:m82HF9BvH06KrieIb6QtBXssL4I24s+uNGnYHcccguY=,tag:pqX9g/3aBBtWrUEDv/ParA==,type:comment]
minio:
    access_key: ENC[AES256_GCM,data:dDLeXTJWIw9DsQ==,iv:SfDRzKqnUjN6q6sFXKvKU1/WNk0TPEZC+pixHQwp8ic=,tag:FL9Sv6mhkqojldyQd91gfg==,type:str]
    secret_key: ENC[AES256_GCM,data:/00gK3NjZU3LeZ7zcJY=,iv:uSi2VLREnLtCyA+sPOj9ZTHUGmFcpDMb6FSaYtJjUrs=,tag:QO0XVFc/y7jjc/hPnznEQA==,type:str]
sops:
    age:
        - recipient: age193z7fgdkklf8f290ye6zj8ee07g6rudls8hhpfqsj6c6tms2fshsxk9lfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYVhURXQ0aGVYeEtiME9O
            a0Y3SzhzTWdpdzJEK0R4Qmw1N0dLVW9xdHdBCmFndmhIQTk5TGc0ZDJaNlVsWjdy
            TVM0NFVzWitNRFpabnkwY3B5bDRxOUEKLS0tIEU3RWNVbmFRcjB3eDFWVHFkNmdj
            V0Nlc3hqUkhjUUt1N250MzljQlpWTlkKcwI7IF1UYt5/wrrfOaDjAxDP49tdLdDU
            xFR/wJSZPuKHI+iJWWGpVAK+MWBcDCa61I2icvYx0j7sTeY0+Qst3A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18p3re8vk23zc4sepnl6f83ljl4zglgxzacuzn9meg4egfhwmmp9scn5d3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTVF0WlRXMDZGK1R0eDNo
            OTVkY0JlMjJjM2NMcitUZnFSaDFxUU01TUZrCnR4WWFQaTlJUlpzOGIxS0dxV3dZ
            ellRYjE5RHRTWitMcDEyVlZWRzZRM3cKLS0tIDVnckZ5SGJSTlpBMzFWeHVrMncx
            OFMvbmtYNjhCUm5WRXRDWVJzNzFLMDQK6tzJ2DJTEcpFvZsyvqXHci7jBInvYYX0
            gn74gTSyqph/ZSpBLHwvAyQIDruMW117HtBnb/FvRPcGCsuzDSQPJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T11:50:14Z"
    mac: ENC[AES256_GCM,data:80VYO8prYDnuCaCGTnvNVt0DlkmAgEXSEvw35g/ryWoBwGv5Ih4a9AKEolYG1dnM6rDEcqKNR/BydWwkBANeTQHeXgnNQy18x3aCARAMBVCdnH1qE0XFbtwwkoaIDwW8bPq0q+WJ0v3XbHHcRt0Lqfg8jb8rrBvaXgY6urBBmwg=,iv:4W6qqZuzOOk7tA38tbUTgFDmXSzq8LIkP2nKDib7j1s=,tag:h26/gENDHlxcC1V+FudUyw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
