#ENC[AES256_GCM,data:C/HCvLtl/4vdlV/gtvy5O7ZxHrFQOUv+0XzOF1Fhiw==,iv:4qQ7CLnpMfvTqb8qXdHRoypzm1xtRXwgNqC74H6xPBE=,tag:cUh1qKPmTl1gLeQ1YwRI8g==,type:comment]
#ENC[AES256_GCM,data:tkbxN2U1rlL0Xn1wR6Wqs7yTMETg61D2xboXjzz/598qpdseIFvhKKs=,iv:2K0fqYHB63gVewDQfjl6Gk+pnVfR3EOzZLvxBi0HS2k=,tag:DSFh/Qd+Jjto/exWYiW+gg==,type:comment]
#ENC[AES256_GCM,data:sqFYtN/rvtHb4PQao50Nn3FqB9V0c/qK7FD7mlnknVmi,iv:ovxGqTnlc6abGPYxnR7ZSsG0BP7TV9AqdyD0WBoAURc=,tag:n1rNvNK72ap6h4qcRVhlPg==,type:comment]
rails:
    master_key: ENC[AES256_GCM,data:73WFr/YFQEyqYqbfCi/2SJj+UBDMxgtNcLtPED9GinA=,iv:I9zWgqVGzcTfIVh1ObqMeZWIGtbgmJY2fhgvq8FTXVg=,tag:s9qPjqoPefXyw+ZMgKoUzg==,type:str]
#ENC[AES256_GCM,data:flQlXuawmXOa7ggZ1jUW8plxvKRDwbHGR9mSHVqiNqs5vF/fr8MzHi4=,iv:yx9T89uNz2XC6WbsZcsD1zA1vKqfGhNLLMD3MU+t2ko=,tag:qG4f2aeZQ96SjdidSaGb3A==,type:comment]
fontawesome:
    auth_token: ENC[AES256_GCM,data:VurD0KnNTKX2tr56xhLLaC06q0Uv00y5wkvzXQ/0+j0BvHyxWqFFT+eX,iv:5eJod2fSHpnBcCzr/aHc51uxhFXmr6xIelN1/lksK2E=,tag:ch9DHo7KqFmdmwkcGVq0uQ==,type:str]
#ENC[AES256_GCM,data:6JbAKi4S5DJEKvDIavH/vmk+b/mr6zZfqYB6HteDtuO6EWcIohIVsnm94Jbx13Fft6ds3mw1W6075iKPX/i3eb3QowFqXQsNPrk=,iv:MR0qIQWo1pU3wzUDSWKr+K/Mh2AF5zwOC6LhHGmIrzk=,tag:J+yNWfAg+Nw05DBzb+wPAg==,type:comment]
minio:
    access_key: ENC[AES256_GCM,data:aCNcMUxbrOCJug==,iv:dz5CdwiREiOipEM4L8MLL6ZMKpCdP8wqxu+yzpUazzA=,tag:Pf1ZcCnLm8I2T/nFSByW3g==,type:str]
    secret_key: ENC[AES256_GCM,data:DJh7dhhvIopOAyet1sE=,iv:1CsmgfYBy02wSCzIBYIMFxYRX7+l6kR2GIbOXYznu/s=,tag:4SYUKKaO9msPEJ0y0DTW0A==,type:str]
#ENC[AES256_GCM,data:K6YJUM23DW71BuLL9FBCAyGIJvzZvXfj8DM4RVcRew8j4kHH,iv:yuRDVYLHPT70odsvhaiShrpbXOSwfwPRj8jL/CVBxKM=,tag:A+8OoQfIx1/2fDORf5oIKg==,type:comment]
credentials:
    secret_key_base: ENC[AES256_GCM,data:R7LPOlKFcCXNmLYJWemt8OtWY2yV2GoHK5K5rX93jyLmLb3VTcEc2Q5ELT+C7bYiyvq+LxCwvg9IgwCHS0wjATr6PMeT7UR5dtqI3iVKQ++mjn6TkNtXp6TFxaLIC1QqIW77JJEdUU0Y1Wh0gjS1AsZiVI8MeQFifgLIugFu1OM=,iv:9WfZlEaUmUJ8iOOQZK+AD3UvQt8PDfo5XnwnbZnQIbY=,tag:5RLcV31Affk2NKUVwXWGww==,type:str]
    mailtrap:
        username: ENC[AES256_GCM,data:XRPO,iv:/hXmD1hJwueIpB23n8ktrcIBsBWZsSIzTEZ22vtLNoA=,tag:vA3jWPISneauW9TFJ0B/9g==,type:str]
        password: ENC[AES256_GCM,data:YK5jX62s+zL+FfvxFfrdEu2f8zwc4O1rFiRPjsG86ns=,iv:pcHZTdBrhDJSP3M2ECERTXszD/gGiqyK3vgTLGvPJIk=,tag:MP41zc1u7n0qeW2eofwMWA==,type:str]
    sentry_dsn: ENC[AES256_GCM,data:hxH8gAjkw1LckKqGxPvrqMijS2+r5RnSp8r1uivdPcoQUK92TLrbzIWpfoYOQMMnacedBW05rTXHZd5M7dcov5spzmDDQMGgAT4NpOplPxc08tkYFVhRcyO/ypg00TA=,iv:nw9Fywm+SmhnDVfI73VboRGWFjMYEITPzucL7OoZDus=,tag:hx0gRRa+yQdsvi5wUrVZGA==,type:str]
    sentry:
        frontend_dsn: ENC[AES256_GCM,data:8jiEaj0RGmhU0Bx3OTRap8dtrtKWjWpaU0WU45c22gDIGRNtC+mzJTbM9xjC27S9mzzixUDK4FWNXK/zwwIvYr8/V0Ki9EMgyLig/HZ5Zk8TbkkMVlExxH2W5uNo6EQ=,iv:SS0Pmb6h4iAOTaKxjifurR+/7Qu2LTF1qL7YhwsDlQU=,tag:dzwbDD4tBMENa9Q3eC9YMA==,type:str]
        blocknote_converter_dsn: ENC[AES256_GCM,data:/gUtXgfihX9XU6DooAw9eAaGkTvULE+yQ9qjU/Zc27JKVHVw198JLjDza8ALf2UJ+3vrpiQ/hc0q4beVihMo582+dF4S1ZgjKYx15YG9tQgJgyfYhANVFrtUn5ZiUKw=,iv:jWAYzlQ1qXdqL/gSi+YMIDbWht/cUrbY5jAYanybygs=,tag:tePzKYs+Kt3TkIdn531oLA==,type:str]
    active_record_encryption:
        primary_key: ENC[AES256_GCM,data:wYGa+41lo+o5D2S0EJmLQfZtt86WMi/OPdWevw1KtfE=,iv:z5CAjhWLcId3R5YkBuFbEOXi7MSzPL2vnOkFRf2M6f8=,tag:BxyfRCWkyowmznDWe0G1Sw==,type:str]
        deterministic_key: ENC[AES256_GCM,data:4h85xIRLoIdhiuEY+eUWLsSjoy5NTjJopaaTHXMEm7U=,iv:FHKAjkwqIzJvIlf7xnfbOFppg8ADM6b9Afmj0wdHStQ=,tag:c/9BO0pUuvsC4nz2QHfTwA==,type:str]
        key_derivation_salt: ENC[AES256_GCM,data:84wu5vRszoxMc5K+qP8cUp33j/kQcN3WtVI6WAIwK+k=,iv:Y3g5w9rN067Hgy4O4VB6fg8sEyimBQRShhL1XiUbXpE=,tag:rZEWPlQXl0gLmyu2GOsbWg==,type:str]
    formula_eval:
        jwt_secret_key: ENC[AES256_GCM,data:EWXUsCy7x1bXF18kAiDZxMpTnhI7I1D9XDPoxJn8O3jY4LQQflr7M48jyELJmQtiZAEE9wLvZsq+yVOzoFGiEybmHUrSM1pNwv2JDWfX9a9o2NH6GKiNhWjlcL7Ly7Q3LPmPKVbMfBVEYAwDdj/mWJjRarRlJ1OTfVNCheGz5l4=,iv:pCc9ifudr3YpObRativq54e8RZnwzNXI+mrxyUiPUgc=,tag:WcKrnKWiyW4xBxWncGwQaA==,type:str]
    recaptcha:
        site_key: ENC[AES256_GCM,data:qym8bp9kRL9ZniJnqD8rXdtj09327iVbGjOdz2QiMydbO3QTPLSFMQ==,iv:rMLmU2PSaNZ4KsxwH7azHkzAjBCngO0L9y4HjEHRGfs=,tag:tk9jSPbkgdIcerl86+8hAg==,type:str]
        secret_key: ENC[AES256_GCM,data:VEEJm9yqp+SEycK2CJSGozVyUN3SvVQKV5QgVq+IkdgVV9H/mdfxhw==,iv:csWf7ZyxH8WhDZWWLveAMO0IEbS6HCiuhWZSAh862Tc=,tag:1EJC16caskVkV17cDENaCg==,type:str]
    google_tag_manager_id: ENC[AES256_GCM,data:V1mGFyoEw5BP2mNO,iv:7mKxNaqgxMBvb+Jvphd64DxOAeQ67nEOyl/f3S0Iukk=,tag:RheIVNmTSL+JuAZ5VfbjGw==,type:str]
    livechat:
        tawk_site_id: ENC[AES256_GCM,data:sVGC/H+Jt0f7hsuRDImf6tts0Ql2EIU6q2Tg5UWvnvMFQw==,iv:DSQUHdrpUOPkoFAdiaW6wNQsmur8pOtSLmpj9Y00J4U=,tag:EAZBfWqWC6nOKXKAtRYdiw==,type:str]
        tawk_api_key: ENC[AES256_GCM,data:inSEB8SIKTDaa83RODKgoliZ39hU26E+Pcd50c1HlUfmf2xhZw/ObA==,iv:/znTN6s2Xxb/E9wJL0Y6gI99W2qN4gDJ4tspRqYGYHA=,tag:xm8Z1njZb4CQiJixCdHGFA==,type:str]
    ckeditor:
        license_key: ENC[AES256_GCM,data:m51JeS234AiU8XMjlICNK9F4rYcODuChjWFSHjehAmrVCvRBFWhfEwCwHejaaH7KcMw5KUzzrxb8Z9S6RNdGVW4uIxxpsUjXSWlmfBYUMQbK+ODqGC5U64dGUm3zSIzhQ2kEeFKvQlRCrbDdvT/6gc+sZYFLZexJv3BPTfCjpabAGTuOW9KlDdGvfuC87VUeMCff1w0xx84uGVb7+mmsCCPANDnLT/MnuxNGs5Hhr+pixCQaEXzUM875nmlrB4x7rykUN+nrKfQBooETGja1TgaeeuSdcRwFenLymUKf/L25COZZ4XoKFtDNGIN1u/zFLdr/zlp7fdtu1LwCvuMVn7WF0AW8Om0vdugX0c1h6gSuPSq+poOqYZar4qQhpX/s1usZXmfiC0HFp4K7WYkGqjmRdC4yk7A/1hGGdxQQKM1AazBIWpBVWeL9HXy9LnFSXFaowbHZPQjqKGAv036OJPcK6imfrwVG47E/8AnbBqsoYk5yCLhxklwmh5rlLL6g0LTSEX24fJwmzz7vM8YxMRjiJ5ZS3ye7+UD3Qod8C3rYYnjnrC5G58AqUcfEhetojf1BDlyHdX+uB4INKI8Zb33GPLmjR2HIvJ6gjxEz7xz2yJ2Ix7XHtpDxYubeaEAM//7XFev7PMd4RyFUNLorS3cxv6hR8x8XjAaFhXsOw4c+yXXqI/PqU42JRyq8nr5Abz3qN2wnKZ5V/Nr/ZkMvcd6KAtNUHyih,iv:j4iS9ePuSIc/5heu2JwxMqw26AexVoZRjhYw95rettE=,tag:qccLpimdAmKYDs3qSDy3ZQ==,type:str]
sops:
    age:
        - recipient: age193z7fgdkklf8f290ye6zj8ee07g6rudls8hhpfqsj6c6tms2fshsxk9lfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMWRVdlV3YVpJUzhidXdO
            UVlFdmlZODQxbFQ5cGo4YTQ2TGc0Q1RNalRrClNGMDd5U2lGYm1jT2JXeDFFTGhs
            ZCtaNjdSTVZXSlpUa0xsMjlVclFzMG8KLS0tIGxndGFscjhEMy9uRXRHVmVlUDBL
            eWZDTmxuQnpka1Z6SFhwNGxmNVY4Y00KC1eaMm9fAsXIf3mIcNcQnoj0F2mp06/t
            S3TJUXvBfMc/J7isdWvS6B/c49WlQNey+l9RtzG6K2J6lzOLcmGaUg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18p3re8vk23zc4sepnl6f83ljl4zglgxzacuzn9meg4egfhwmmp9scn5d3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4K1NmaUY0Y1Bza3BNZnI4
            RnZhczQxTkdzOVRvSnlnZ21MNGp5TUpUeUJZCjRMRFJDNVRZUWswSUMrYUpHOHVL
            SVBBNGF2cHFaNG5NV3hTTzFCMzB4ZGMKLS0tIGMxZkVrQ21ieFh1aXFveGNlUnJO
            ck9aZGJLWllQelRid0JOVVJHS2dTWTAKRJ4U6jol7b5GdYFZJUshjvDmR3DHivW/
            NoFOS7e+SeE7QDUNoBGvnSDx/UaAWyjWYk/MlbhJ6XhO57cMDWHOsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T11:44:37Z"
    mac: ENC[AES256_GCM,data:sPOntTPcH/x7O1Ck+EhinjSrXScPQh8ZQh19Gj414WeecwfyaBmaBiAIimc3e3tXcniOaot/Xy1Qaa9UJw4YBOdVzylAHeMkvvY4RZK+heoPmeNy9Zxo6m2xzv7Vjccjb8oA3kV6QyG60XSnbCg6iwf8HS8zm6+0o+tzK/GMyPI=,iv:xPZFwTWr4BAsi7jX286BzyU6yrYurzDFxMYMQsocC/w=,tag:vpF12VPrQnXtcbrXysw3cA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
