// JsFromRoutes CacheKey 8cbc54b4038944f7861968b326360aa9
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  edit: /* #__PURE__ */ definePathHelper('get', '/users/:user_id/avatar/edit'),
  update: /* #__PURE__ */ definePathHelper('patch', '/users/:user_id/avatar'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/users/:user_id/avatar'),
}
