// JsFromRoutes CacheKey b6fdbcef05c89e533270890f6b36180a
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  update: /* #__PURE__ */ definePathHelper('patch', '/users/:user_id/user_properties/:id'),
}
