// JsFromRoutes CacheKey 19cdbdb448d8c473ed293ceb4b5734a8
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as documents } from './DocumentsApi'
export { default as spaces } from './SpacesApi'
