// JsFromRoutes CacheKey 7d45531fec51d9000eeb78714c951a1a
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/public_links/:public_link_id/allowed_emails'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/public_links/:public_link_id/allowed_emails/:email'),
}
