// JsFromRoutes CacheKey cca8afa316064a833fddbb427092f26a
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/users/:user_id/api_tokens'),
  create: /* #__PURE__ */ definePathHelper('post', '/users/:user_id/api_tokens'),
  new: /* #__PURE__ */ definePathHelper('get', '/users/:user_id/api_tokens/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/users/:user_id/api_tokens/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/users/:user_id/api_tokens/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/users/:user_id/api_tokens/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/users/:user_id/api_tokens/:id'),
}
