// JsFromRoutes CacheKey aaae61772056fbbf3edfb1d9bf7649fc
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/users/:user_id/api_tokens'),
  create: /* #__PURE__ */ definePathHelper('post', '/users/:user_id/api_tokens'),
  new: /* #__PURE__ */ definePathHelper('get', '/users/:user_id/api_tokens/new'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/users/:user_id/api_tokens/:id'),
}
