// JsFromRoutes CacheKey 91e88153bc549dd4aa0bf71c026f7b40
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/attachments'),
  show: /* #__PURE__ */ definePathHelper('get', '/attachments/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/attachments/:id'),
}
