// JsFromRoutes CacheKey 1b39695614bf85b4fb82458d8edd15c7
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/attachments'),
  show: /* #__PURE__ */ definePathHelper('get', '/attachments/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/attachments/:id'),
}
