// JsFromRoutes CacheKey ad2e45f77f157f1205a3a76fd7f0733b
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/spaces/:space_npi/automations'),
  create: /* #__PURE__ */ definePathHelper('post', '/spaces/:space_npi/automations'),
  new: /* #__PURE__ */ definePathHelper('get', '/spaces/:space_npi/automations/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/spaces/:space_npi/automations/:npi/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/spaces/:space_npi/automations/:npi'),
  update: /* #__PURE__ */ definePathHelper('patch', '/spaces/:space_npi/automations/:npi'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/spaces/:space_npi/automations/:npi'),
}
