// JsFromRoutes CacheKey 4f399e0f689c5f1bd7b2790998f44f77
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/s/:space_npi/automations'),
  create: /* #__PURE__ */ definePathHelper('post', '/s/:space_npi/automations'),
  new: /* #__PURE__ */ definePathHelper('get', '/s/:space_npi/automations/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/s/:space_npi/automations/:npi/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/s/:space_npi/automations/:npi'),
  update: /* #__PURE__ */ definePathHelper('patch', '/s/:space_npi/automations/:npi'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/s/:space_npi/automations/:npi'),
}
