// JsFromRoutes CacheKey ee439e1a9f5b2176da6a53fe7661e967
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/s/:space_id/automations'),
  create: /* #__PURE__ */ definePathHelper('post', '/s/:space_id/automations'),
  new: /* #__PURE__ */ definePathHelper('get', '/s/:space_id/automations/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/s/:space_id/automations/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/s/:space_id/automations/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/s/:space_id/automations/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/s/:space_id/automations/:id'),
}
