// JsFromRoutes CacheKey 2bce7be2b0ce119fa079907742b8faa3
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  edit: /* #__PURE__ */ definePathHelper('get', '/users/:user_id/avatar/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/users/:user_id/avatar'),
  update: /* #__PURE__ */ definePathHelper('patch', '/users/:user_id/avatar'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/users/:user_id/avatar'),
}
