// JsFromRoutes CacheKey f8776aa3a7ccb80e0e594d333118b302
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/d/:document_npi/comments'),
  create: /* #__PURE__ */ definePathHelper('post', '/d/:document_npi/comments'),
  new: /* #__PURE__ */ definePathHelper('get', '/d/:document_npi/comments/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/d/:document_npi/comments/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/d/:document_npi/comments/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/d/:document_npi/comments/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/d/:document_npi/comments/:id'),
}
