// JsFromRoutes CacheKey 0a80f28f99216afdc2886864f1ea6ecd
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/comments'),
  create: /* #__PURE__ */ definePathHelper('post', '/comments'),
  new: /* #__PURE__ */ definePathHelper('get', '/comments/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/comments/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/comments/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/comments/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/comments/:id'),
}
