// JsFromRoutes CacheKey 24943b7d873f850ede90c6e442e4540e
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  restore: /* #__PURE__ */ definePathHelper('post', '/comments/:id/restore'),
  index: /* #__PURE__ */ definePathHelper('get', '/comments'),
  create: /* #__PURE__ */ definePathHelper('post', '/comments'),
  new: /* #__PURE__ */ definePathHelper('get', '/comments/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/comments/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/comments/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/comments/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/comments/:id'),
}
