// JsFromRoutes CacheKey 2de21b903ca45f013930930520a4af15
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/documents'),
  show: /* #__PURE__ */ definePathHelper('get', '/documents/:id'),
  create: /* #__PURE__ */ definePathHelper('post', '/spaces/:space_npi/documents'),
  new: /* #__PURE__ */ definePathHelper('get', '/spaces/:space_npi/documents/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/spaces/:space_npi/documents/:id/edit'),
  update: /* #__PURE__ */ definePathHelper('patch', '/spaces/:space_npi/documents/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/spaces/:space_npi/documents/:id'),
}
