// JsFromRoutes CacheKey c53eeddd5368bcd9c62be57a99a4cba3
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/documents'),
  show: /* #__PURE__ */ definePathHelper('get', '/documents/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/documents/:id'),
  create: /* #__PURE__ */ definePathHelper('post', '/spaces/:space_npi/documents'),
  new: /* #__PURE__ */ definePathHelper('get', '/spaces/:space_npi/documents/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/spaces/:space_npi/documents/:id/edit'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/spaces/:space_npi/documents/:id'),
}
