// JsFromRoutes CacheKey b122e1841b60e69925330bd706ec3363
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  eval: /* #__PURE__ */ definePathHelper('post', '/formulas/eval'),
}
