// JsFromRoutes CacheKey 5655e1bc6f04a34622d4ea22e53b0c61
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/imports'),
  create: /* #__PURE__ */ definePathHelper('post', '/imports'),
  new: /* #__PURE__ */ definePathHelper('get', '/imports/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/imports/:npi/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/imports/:npi'),
  update: /* #__PURE__ */ definePathHelper('patch', '/imports/:npi'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/imports/:npi'),
}
