// JsFromRoutes CacheKey 82c66b89efeaa77137b9aada10cdf6a3
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/imports'),
  create: /* #__PURE__ */ definePathHelper('post', '/imports'),
  new: /* #__PURE__ */ definePathHelper('get', '/imports/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/imports/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/imports/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/imports/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/imports/:id'),
}
