// JsFromRoutes CacheKey d4b3608ef9ed470f7c7f806fc3870c47
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  addCommentThread: /* #__PURE__ */ definePathHelper('post', '/inline_comments'),
}
