// JsFromRoutes CacheKey b07bda9f73ad3100b641bcfb56f2c88c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  addCommentThread: /* #__PURE__ */ definePathHelper('post', '/inline_comments/threads'),
  getCommentThread: /* #__PURE__ */ definePathHelper('get', '/inline_comments/threads/:thread_id'),
  addComment: /* #__PURE__ */ definePathHelper('post', '/inline_comments/threads/:thread_id/comments'),
  updateComment: /* #__PURE__ */ definePathHelper('put', '/inline_comments/threads/:thread_id/comments/:comment_id'),
}
