// JsFromRoutes CacheKey 35d4365c9c13ce88b8b3c0fc7232ac76
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/onboarding_contents/*path'),
}
