// JsFromRoutes CacheKey 11712d3d1574f5ce9430d1cd65cee7e4
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/public_links'),
  create: /* #__PURE__ */ definePathHelper('post', '/public_links'),
  new: /* #__PURE__ */ definePathHelper('get', '/public_links/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/public_links/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/public_links/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/public_links/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/public_links/:id'),
}
