// JsFromRoutes CacheKey d8824e99c543f4fe76ec4024a991ff0c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/public/:npi'),
  attachment: /* #__PURE__ */ definePathHelper('get', '/public/attachments/:id'),
}
