// JsFromRoutes CacheKey f812c9ab1cab4c74f1e0d9c6cbf31050
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/public/:id'),
  attachment: /* #__PURE__ */ definePathHelper('get', '/public/attachments/:id'),
}
