// JsFromRoutes CacheKey 0af173c45ef5e75de1e9a71204baf2a7
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/public/:npi'),
  attachment: /* #__PURE__ */ definePathHelper('get', '/public/attachments/:id'),
}
