// JsFromRoutes CacheKey b1b91e66680047dc041afdd744414624
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/d/:document_npi/reactions'),
  create: /* #__PURE__ */ definePathHelper('post', '/d/:document_npi/reactions'),
  show: /* #__PURE__ */ definePathHelper('get', '/d/:document_npi/reactions/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/d/:document_npi/reactions/:id'),
}
