// JsFromRoutes CacheKey 731ac444946b3a1780d67be505a687b5
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/search'),
}
