// JsFromRoutes CacheKey 8674c5bbc65fe614d0383bd8db86c3e3
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  reorderHierarchy: /* #__PURE__ */ definePathHelper('put', '/spaces/:space_npi/reorder_hierarchy'),
  suggestOwners: /* #__PURE__ */ definePathHelper('get', '/spaces/suggest_owners'),
  index: /* #__PURE__ */ definePathHelper('get', '/spaces'),
  create: /* #__PURE__ */ definePathHelper('post', '/spaces'),
  new: /* #__PURE__ */ definePathHelper('get', '/spaces/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/spaces/:npi/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/spaces/:npi'),
  update: /* #__PURE__ */ definePathHelper('patch', '/spaces/:npi'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/spaces/:npi'),
}
