// JsFromRoutes CacheKey ec36e27233a8605a0cdcc9b4eb1bfecd
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  suggestOwners: /* #__PURE__ */ definePathHelper('get', '/s/suggest_owners'),
  reorderHierarchy: /* #__PURE__ */ definePathHelper('put', '/s/:id/reorder_hierarchy'),
  sidebar: /* #__PURE__ */ definePathHelper('get', '/s/:id/sidebar'),
  index: /* #__PURE__ */ definePathHelper('get', '/s'),
  create: /* #__PURE__ */ definePathHelper('post', '/s'),
  new: /* #__PURE__ */ definePathHelper('get', '/s/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/s/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/s/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/s/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/s/:id'),
}
