// JsFromRoutes CacheKey c151a6387cc66a12b4bb6e73846291ff
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  reorderHierarchy: /* #__PURE__ */ definePathHelper('put', '/spaces/:space_id/reorder_hierarchy'),
  create: /* #__PURE__ */ definePathHelper('post', '/spaces'),
  new: /* #__PURE__ */ definePathHelper('get', '/spaces/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/spaces/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/spaces/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/spaces/:id'),
}
