// JsFromRoutes CacheKey ce08cd07b8135a67f4cd1d18ef699879
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  suggest: /* #__PURE__ */ definePathHelper('get', '/s/:space_npi/tags/suggest'),
}
