// JsFromRoutes CacheKey c0a10582f907562d3dcf9f956a4447b3
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  suggest: /* #__PURE__ */ definePathHelper('get', '/s/:space_id/tags/suggest'),
}
