// JsFromRoutes CacheKey cfdd2cd9affc14ba3375bcd11c52dd72
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/users/:user_id/user_properties'),
  create: /* #__PURE__ */ definePathHelper('post', '/users/:user_id/user_properties'),
  new: /* #__PURE__ */ definePathHelper('get', '/users/:user_id/user_properties/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/users/:user_id/user_properties/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/users/:user_id/user_properties/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/users/:user_id/user_properties/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/users/:user_id/user_properties/:id'),
}
