// JsFromRoutes CacheKey ea43b868668bd6e8d210f96d331e721c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/users'),
  show: /* #__PURE__ */ definePathHelper('get', '/users/:id'),
}
