// JsFromRoutes CacheKey 03e1bdd9f8c03bf517e1da85a5fa7cdc
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  suggestions: /* #__PURE__ */ definePathHelper('get', '/users/suggestions'),
  index: /* #__PURE__ */ definePathHelper('get', '/users'),
  show: /* #__PURE__ */ definePathHelper('get', '/users/:id'),
}
