// JsFromRoutes CacheKey e7497b80ccb1770227ecd702d6461f16
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  suggestions: /* #__PURE__ */ definePathHelper('get', '/users/suggestions'),
  index: /* #__PURE__ */ definePathHelper('get', '/users'),
  show: /* #__PURE__ */ definePathHelper('get', '/users/:id'),
}
