// JsFromRoutes CacheKey f4f45aa083d5a0209c4db901169e3962
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/spaces/:space_npi/documents/:document_id/versions'),
}
