// JsFromRoutes CacheKey d5515b15cb4ac0cf4d7b3b253f99ed6b
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/spaces/:space_npi/documents/:document_id/versions'),
  create: /* #__PURE__ */ definePathHelper('post', '/spaces/:space_npi/documents/:document_id/versions'),
}
