// JsFromRoutes CacheKey a5634e1cbc23e34226417291101e97a3
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/spaces/:space_id/documents/:document_id/versions'),
}
