// JsFromRoutes CacheKey f568c9de17843e1cc5d97d5d519aa6ff
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/spaces/:space_npi/database'),
}
