// JsFromRoutes CacheKey 37f9a11bb6e45d17e90408c936b6d31a
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/d/:document_id/object_mentions'),
}
