// JsFromRoutes CacheKey 3067405f77b04f01e7a6d139de194b9c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/d/:document_id/object_references'),
}
