// JsFromRoutes CacheKey 9daf8d69a0e6c7d74f2311ae027dfe6e
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/d/:document_npi/reactions'),
  create: /* #__PURE__ */ definePathHelper('post', '/d/:document_npi/reactions'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/d/:document_npi/reactions/:id'),
}
