// JsFromRoutes CacheKey a6fea046485ff92d07afaba0888504c2
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/d/:document_npi/reactions'),
}
