// JsFromRoutes CacheKey 46c1304058291b6b37990a39751ff302
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/spaces/:space_npi/documents/:document_id/versions'),
  create: /* #__PURE__ */ definePathHelper('post', '/spaces/:space_npi/documents/:document_id/versions'),
  show: /* #__PURE__ */ definePathHelper('get', '/spaces/:space_npi/documents/:document_id/versions/:id'),
}
