// JsFromRoutes CacheKey 45add10b733a0d3e97204741599ae712
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/d/:document_id/versions'),
  create: /* #__PURE__ */ definePathHelper('post', '/d/:document_id/versions'),
  show: /* #__PURE__ */ definePathHelper('get', '/d/:document_id/versions/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/d/:document_id/versions/:id'),
}
