// JsFromRoutes CacheKey 5cdad9b80b8003ffd118385671ad80f7
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/spaces/:space_npi/documents/:document_id/versions'),
  create: /* #__PURE__ */ definePathHelper('post', '/spaces/:space_npi/documents/:document_id/versions'),
  show: /* #__PURE__ */ definePathHelper('get', '/spaces/:space_npi/documents/:document_id/versions/:id'),
}
