// JsFromRoutes CacheKey a1347906372f667e5f81c90382cde66b
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/t/:table_npi/comments'),
  create: /* #__PURE__ */ definePathHelper('post', '/t/:table_npi/comments'),
  new: /* #__PURE__ */ definePathHelper('get', '/t/:table_npi/comments/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/t/:table_npi/comments/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/t/:table_npi/comments/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/t/:table_npi/comments/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/t/:table_npi/comments/:id'),
}
