// JsFromRoutes CacheKey deb91b7f5530a75d8b18cf5ed4e67775
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/reactions'),
  create: /* #__PURE__ */ definePathHelper('post', '/reactions'),
  show: /* #__PURE__ */ definePathHelper('get', '/reactions/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/reactions/:id'),
}
