// JsFromRoutes CacheKey d6bd8fb9f6a3250d8b530007337543ce
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/d/:document_id/tags'),
  tableTags: /* #__PURE__ */ definePathHelper('get', '/t/:table_id/tags'),
  create: /* #__PURE__ */ definePathHelper('post', '/d/:document_id/tags'),
  createPost: /* #__PURE__ */ definePathHelper('post', '/t/:table_id/tags'),
}
