// JsFromRoutes CacheKey a0efab2f8c1019c67208cd8ce5d95522
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/d/:document_npi/tags'),
  create: /* #__PURE__ */ definePathHelper('post', '/d/:document_npi/tags'),
}
