// JsFromRoutes CacheKey 9a63ff5c6306afaa490e518e894af862
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/d/:document_npi/tags'),
  tableTags: /* #__PURE__ */ definePathHelper('get', '/t/:table_npi/tags'),
  create: /* #__PURE__ */ definePathHelper('post', '/d/:document_npi/tags'),
  createPost: /* #__PURE__ */ definePathHelper('post', '/t/:table_npi/tags'),
}
