name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  RAILS_ENV: test
  DATABASE_URL: postgres://postgres:password@localhost/postgres

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1.33.2
        with:
          bunder-cache: true
      - uses: hoverkraft-tech/compose-action@v2.0.1
      - name: Run tests
        run: rails test