name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  RAILS_ENV: test
  DATABASE_URL: postgres://postgres:password@localhost/postgres

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm ci
        working-directory: formula
      - run: npm run build --if-present
        working-directory: formula
      - uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          services: |
            postgresql
            redis
      - name: Setup the database
        run: bin/rails db:setup
      - name: Run tests
        run: bin/rails test